# Generated by Django 4.2.9 on 2025-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='map_location_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
