# Generated by Django 4.2.9 on 2025-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_map_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='map_location_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
