# Generated by Django 4.2.9 on 2025-01-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_map_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='icon',
        ),
    ]
