# Generated by Django 4.2.9 on 2025-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_interest_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
